"""empty message

Revision ID: 74e52b265581
Revises: 044e42db0e59
Create Date: 2018-10-22 13:01:33.141500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74e52b265581'
down_revision = '044e42db0e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
