"""empty message

Revision ID: b01de4fa3f6e
Revises: 74e52b265581
Create Date: 2018-10-22 13:01:43.482807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01de4fa3f6e'
down_revision = '74e52b265581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_date')
    # ### end Alembic commands ###
